=== drolin9/XML_DTD/TP1_Exercise_1_DTD.dtd
<!--
Travail TP1 numero 2
IFT-1152
Karl Rushford
code permanent RUSK28078403
matricule 20002954
remise le 13 fevrier 2018
-->




<!ELEMENT books (book+)> 

<!ELEMENT book (title, logo?, author-list, copyright, nbpages, editor?)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT logo (#PCDATA)>   <!-- a finir -->

<!ELEMENT author-list (author+)>
<!ELEMENT author (firstname, lastname)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>

<!ELEMENT copyright (#PCDATA) >
<!ELEMENT nbpages (#PCDATA) >
<!ELEMENT editor (#PCDATA) >

<!ATTLIST book isbn CDATA #IMPLIED >  <!-- optionnel -->
<!ATTLIST book language (English|Français|Espagnol) #REQUIRED> <!-- obligatoire -->
<!ATTLIST logo file CDATA #IMPLIED>   <!-- optionnel -->




<!--
	pour une valeur par default, 
	<!ATTLIST book language CDATA "Francais">
	donc si on mettait <book></book> la valeur de l'attribut language sera francais par default
	
	pour une valeur fixe
	<!ATTLIST book language CDATA #FIXED "anglais">
	
? : signifie optionnel (0 ou 1 fois)
* : signifie 0 à infini
+ : signifie 1 à infini
  : signifie exactement 1
, : signifie dans l’ordre
| : signifie le ou logique
	
<!ENTITY troll "test troll" >	
	
-->

=== drolin9/XML_DTD/TP1_Exercise_1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!--
Travail TP1 numero 1
IFT-1152
Karl Rushford


-->

<!DOCTYPE books SYSTEM "TP1_Exercise_1_DTD.dtd" >


<books>

	<book isbn="5-2341-9384-2" language="English">
		<title>The XMLSPY Game</title>
		<logo file="cover.gif"/>
		<author-list>
			<author>
				<firstname>David</firstname>
				<lastname>Smith</lastname>
			</author>
			<author>
				<firstname>Frank</firstname>
				<lastname>Smith</lastname>
			</author>
		</author-list>
		<copyright>1999</copyright>
		<nbpages>330</nbpages>
	</book>
	
	<book isbn="0-596-00420-6" language="English">
		<title>Learning XML</title>
		<logo file="cuit_cuit.gif"/>
		<author-list>
			<author>
				<firstname>Erik</firstname>
				<lastname>T. Ray</lastname>
			</author>
			<author>
				<firstname>Bob</firstname>
				<lastname>E. Ray</lastname>
			</author>
		</author-list>
		<copyright>2003</copyright>
		<nbpages>400</nbpages>
		<editor>O&apos;Reilly</editor>
	</book>
	
	<book isbn="0-596-00048-0" language="English">
		<title>JavaScript: The Definitive Guide</title>
		<author-list>
			<author>
				<firstname>David</firstname> 
				<lastname>Flanagan</lastname>
			</author>
		</author-list>  
		<copyright>2002</copyright>
		<nbpages>916</nbpages>
		<editor>O&apos;Reilly</editor>
	</book>
	
	
</books>

<!--   				

<!DOCTYPE racine [ ]>  ecrire le dtd entre [] pour les dtd interne
<firstname>&troll;</firstname> pour APPELER une variable definie dans le dtd (entity)



 -->
